# Generated by Django 3.2.12 on 2023-01-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankInForm', '0003_newaccountform'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassbookInform',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BankInForm.mybasemodel')),
                ('branch', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('tel_no', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('MICR_code', models.IntegerField()),
                ('IFSC_code', models.IntegerField()),
                ('account_type', models.CharField(max_length=255)),
                ('account_no', models.IntegerField()),
                ('passbook_no', models.IntegerField()),
                ('acc_open_date', models.DateTimeField(auto_now_add=True)),
                ('passbook_type', models.CharField(max_length=100)),
                ('self_address', models.CharField(max_length=255)),
            ],
            bases=('BankInForm.mybasemodel',),
        ),
    ]
