# Generated by Django 3.2.12 on 2023-01-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_passbookinform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passbookinform',
            name='IFSC_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passbookinform',
            name='account_no',
            field=models.CharField(max_length=100),
        ),
    ]
