# Generated by Django 3.2.12 on 2023-01-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_bankhrinform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankhrinform',
            old_name='branch',
            new_name='branch_name',
        ),
    ]
