# Generated by Django 3.2.12 on 2023-01-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankInForm', '0003_newaccountform'),
        ('Employee', '0005_rename_branch_bankhrinform_branch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBook',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BankInForm.mybasemodel')),
                ('account_no', models.IntegerField()),
                ('rupees', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('signature', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('day', models.CharField(max_length=100)),
            ],
            bases=('BankInForm.mybasemodel',),
        ),
    ]
