# Generated by Django 3.2.12 on 2023-01-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationsOfBank',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BankInForm.mybasemodel')),
                ('b_name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=155)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('employee', models.IntegerField()),
                ('department', models.IntegerField()),
            ],
            bases=('BankInForm.mybasemodel',),
        ),
    ]
