# Generated by Django 3.2.12 on 2023-01-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankInForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLeader',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BankInForm.mybasemodel')),
                ('boss_name', models.CharField(max_length=255)),
                ('address', models.CharField(default=True, max_length=155)),
                ('educations', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=155)),
                ('branch', models.CharField(max_length=155)),
                ('payment', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
            bases=('BankInForm.mybasemodel',),
        ),
    ]
