# Generated by Django 3.2.12 on 2023-01-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankInForm', '0002_bankleader'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAccountForm',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BankInForm.mybasemodel')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=155)),
                ('district', models.CharField(max_length=100)),
                ('catrgory', models.CharField(max_length=100)),
                ('equcational_qulification', models.CharField(max_length=155)),
                ('occupation', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
            ],
            bases=('BankInForm.mybasemodel',),
        ),
    ]
