# Generated by Django 3.2.12 on 2023-01-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BankInForm', '0003_newaccountform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLogin',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BankInForm.mybasemodel')),
                ('user_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=255)),
                ('acco_no', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('password', models.IntegerField()),
            ],
            bases=('BankInForm.mybasemodel',),
        ),
    ]
