# Generated by Django 3.2.12 on 2023-01-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankInForm', '0003_newaccountform'),
        ('Accountant', '0002_accountsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRegister',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BankInForm.mybasemodel')),
                ('birth_date', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('accou_type', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=255)),
                ('password', models.IntegerField()),
                ('password_confirmation', models.IntegerField()),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
            ],
            bases=('BankInForm.mybasemodel',),
        ),
    ]
