# Generated by Django 3.2.12 on 2023-01-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankInForm', '0003_newaccountform'),
        ('Accountant', '0003_accountregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReport',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BankInForm.mybasemodel')),
                ('t_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('balance_after_transaction', models.IntegerField()),
            ],
            bases=('BankInForm.mybasemodel',),
        ),
        migrations.AlterField(
            model_name='accountregister',
            name='birth_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountregister',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
