# Generated by Django 3.2.12 on 2023-02-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankInForm', '0003_newaccountform'),
        ('Accountant', '0005_deleteaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawMoneyFromBank',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BankInForm.mybasemodel')),
                ('name', models.CharField(max_length=255)),
                ('b_name', models.CharField(max_length=100)),
                ('account_no', models.IntegerField()),
                ('rupees', models.IntegerField()),
                ('words_rupees', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('signature', models.CharField(max_length=100)),
            ],
            bases=('BankInForm.mybasemodel',),
        ),
    ]
