# Generated by Django 3.2.12 on 2023-02-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankInForm', '0003_newaccountform'),
        ('Accountant', '0006_withdrawmoneyfrombank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowAccount',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BankInForm.mybasemodel')),
                ('account_no', models.IntegerField()),
                ('acco_holder_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('balance_amount', models.IntegerField()),
            ],
            bases=('BankInForm.mybasemodel',),
        ),
    ]
